export const TestPageActionTypes = {
  FETCH_TEST_START: 'FETCH_TEST_START',
  FETCH_TEST_SUCCESS: 'FETCH_TEST_SUCCESS',
  FETCH_TEST_FAILURE: 'FETCH_TEST_FAILURE',
  SET_QUESTION_NO: 'SET_QUESTION_NO',
  SET_SINGLE_CHOICE_RESPONSE: 'SET_SINGLE_CHOICE_RESPONSE',
  ADD_MULTIPLE_CHOICE_RESPONSE: 'ADD_MULTIPLE_CHOICE_RESPONSE',
  REMOVE_MULTIPLE_CHOICE_RESPONSE: 'REMOVE_MULTIPLE_CHOICE_RESPONSE',
  SET_TYPED_RESPONSE: 'SET_TYPED_RESPONSE',
};
