const CourseTopicActionTypes = {
  FETCH_COURSE_TOPICS_START: 'FETCH_COURSE_TOPICS_START',
  FETCH_COURSE_TOPICS_SUCCESS: 'FETCH_COURSE_TOPICS_SUCCESS',
  FETCH_COURSE_TOPICS_FAILURE: 'FETCH_COURSE_TOPICS_FAILURE',
};

export default CourseTopicActionTypes;
