export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  FETCH_USER_START: 'FETCH_USER_START',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
};
